classes.dir = target/classes
project.name = helium
project.name.lowercase = helium
principalClass =
customInfoPListContent =
eoAdaptorClassName =
cfBundleVersion =
cfBundleShortVersion =
cfBundleID = is.loftfar
javaVersion = 1.5+
