<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>is.rebbi</groupId>
	<artifactId>helium</artifactId>
	<packaging>woframework</packaging>
	<version>2.0.0-SNAPSHOT</version>
	<name>helium WebObjects Framework</name>
	<url>http://maven.apache.org</url>

	<properties>
		<webobjects.group>com.webobjects</webobjects.group>
		<webobjects.version>5.4.3</webobjects.version>

		<wonder.core.group>wonder.core</wonder.core.group>
		<wonder.ajax.group>wonder.ajax</wonder.ajax.group>
		<wonder.version>8.0.0.slim-SNAPSHOT</wonder.version>

		<cayenne.version>4.1.1</cayenne.version>

		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<build>
		<finalName>${project.artifactId}</finalName>
		<plugins>
			<plugin>
				<groupId>is.rebbi</groupId>
				<artifactId>vermilingua-maven-plugin</artifactId>
				<version>1.0.0-SNAPSHOT</version>
				<extensions>true</extensions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M5</version>
				<configuration>
					<argLine>
		    			--add-exports java.base/sun.security.action=ALL-UNNAMED
					</argLine>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>17</source>
					<target>17</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-site-plugin</artifactId>
				<version>3.0</version>
				<dependencies>
					<dependency>
						<groupId>org.apache.maven.wagon</groupId>
						<artifactId>wagon-ssh</artifactId>
						<version>2.10</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>2.7</version>
				<dependencies>
					<dependency>
						<groupId>org.apache.maven.wagon</groupId>
						<artifactId>wagon-ssh</artifactId>
						<version>2.10</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>

	<distributionManagement>
		<site>
			<id>rebbi</id>
			<name>Rebbi</name>
			<url>scp://root@maven.rebbi.is/rebbi/is.rebbi.maven/html</url>
		</site>
		<repository>
			<id>rebbi</id>
			<name>Rebbi</name>
			<url>scp://root@maven.rebbi.is/rebbi/is.rebbi.maven/html</url>
		</repository>
	</distributionManagement>

	<repositories>
		<repository>
			<id>rebbi</id>
			<name>Rebbi</name>
			<url>https://maven.rebbi.is</url>
			<layout>default</layout>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>wocommunity.releases</id>
			<name>WOCommunity Releases Repository</name>
			<url>https://maven.wocommunity.org/content/groups/public</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>wocommunity.snapshots</id>
			<name>WOCommunity Snapshots Repository</name>
			<url>https://maven.wocommunity.org/content/groups/public-snapshots</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>wocommunity.releases</id>
			<name>WOCommunity Releases Repository</name>
			<url>https://maven.wocommunity.org/content/groups/public</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
		<pluginRepository>
			<id>wocommunity.snapshots</id>
			<name>WOCommunity Snapshots Repository</name>
			<url>https://maven.wocommunity.org/content/groups/public-snapshots</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

	<dependencies>
		<dependency>
			<groupId>${wonder.core.group}</groupId>
			<artifactId>ERExtensions</artifactId>
			<version>${wonder.version}</version>
		</dependency>
		<dependency>
			<groupId>${wonder.ajax.group}</groupId>
			<artifactId>Ajax</artifactId>
			<version>${wonder.version}</version>
			<scope>provided</scope> <!-- Prevents us from Ajax-ing all over AjaxSlim projects -->
		</dependency>
		<dependency>
			<groupId>${wonder.core.group}</groupId>
			<artifactId>ERLoggingReload4j</artifactId>
			<version>${wonder.version}</version>
		</dependency>
		<dependency>
			<groupId>${webobjects.group}</groupId>
			<artifactId>JavaWebObjects</artifactId>
			<version>${webobjects.version}</version>
			<exclusions>
				<exclusion>
					<groupId>${webobjects.group}</groupId>
					<artifactId>JavaXML</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>is.rebbi</groupId>
			<artifactId>rebbi-core</artifactId>
			<version>2.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>is.rebbi</groupId>
			<artifactId>jambalaya</artifactId>
			<version>2.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.apache.cayenne</groupId>
			<artifactId>cayenne-server</artifactId>
			<version>${cayenne.version}</version>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>5.9.1</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>