package is.rebbi.wo.api;

import java.lang.reflect.Type;

import com.webobjects.appserver.WORequest;
import com.webobjects.appserver.WOResponse;
import com.webobjects.eocontrol.EOEditingContext;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableArray;

import er.extensions.appserver.ERXDirectAction;
import is.rebbi.wo.util.USJson;

public abstract class USController extends ERXDirectAction {

	private static NSMutableArray<Class<? extends USController>> _controllers = new NSMutableArray<>();

	private EOEditingContext _ec;

	public USController( WORequest r ) {
		super( r );
	}

	public static void register( Class<? extends USController> controllerClass ) {
		_controllers.addObject( controllerClass );
	}

	public static NSArray<Class<? extends USController>> controllers() {
		return _controllers;
	}

	/**
	 * @return A new editing context for each instance of the controller class.
	 */
	protected EOEditingContext ec() {
		if( _ec == null ) {
			_ec = session().defaultEditingContext();
		}

		return _ec;
	}

	/**
	 * @return An object of class E, created by deserializing the current request.
	 */
	public <E> E in( Class<E> clazz ) {
		return USJson.fromRequest( request(), clazz );
	}

	/**
	 * @return An object of class E, created by deserializing the current request.
	 */
	public <E> E in( Type type ) {
		return USJson.fromRequest( request(), type );
	}

	/**
	 * @return A WOResponse generated by serializing the given object to JSON.
	 */
	public WOResponse out( Object o ) {
		return USJson.response( o );
	}
}